### ISSUE TITLE
Check keeps saying "Expected - Waiting for status to be reported"

### ISSUE THREAD

**Issue by mosherc** [mheap/github-action-required-labels#17]
I keep getting the status below for this check:
![image](https://user-images.githubusercontent.com/7862535/154367390-8a88513f-d14e-4afe-b741-5e1c98789938.png)

Code:
```yml
name: Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  do_not_merge:
    name: Disallow Merging When "do not merge" Label Is Present
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "do not merge"
```

Apparently the workaround is to push an empty commit to re-trigger the action, but this is happening on a lot of our PRs, so it's a little annoying. All of the action runs are successful, I guess it's just not getting reported? It's not happening with any of our other actions.
