### ISSUE TITLE
Idea: make the exit status configurable

### ISSUE THREAD

**Issue by moritzjacobs** [mheap/github-action-required-labels#23]
Hi! Thanks for maintaining this, we use it for a rather complicated PR approval process involving chromatic and it helped us immensely reducing build time!

One small suggestion:

We would love a configuration option to replace `tools.exit.failure` with [`tools.exit.neutral`](https://github.com/JasonEtco/actions-toolkit#toolsexit), so we don't really "fail" the PR but keep it "pending" so to speak.

Maybe something like:

```yaml
- uses: mheap/github-action-required-labels@v1
  with:
    mode: exactly
    count: 1
    exitNeutral: true
    labels: "semver:patch, semver:minor, semver:major"
```

If you consider it but don't have time, I could try and create a pull request, seems to be easy enough. Thank you for consideration!

**Comment by mheap** [comment]
This is now released as v2

```
- uses: mheap/github-action-required-labels@v2
  with:
    mode: minimum
    count: 2
    labels: "community-reviewed, team-reviewed, codeowner-reviewed"
    exit_type: neutral # Can be: failure, neutral or success
```
