### ISSUE TITLE
Labels which is added by action-add-label is not recognized

### ISSUE THREAD

**Issue by tkoyama010** [mheap/github-action-required-labels#33]
Thanks for this action. In our project, we have a problem that github-actions-required-labels do not recognize labels labeled with action-add-label.
https://github.com/pyvista/pyvista/runs/7063771018?check_suite_focus=true
This is the yaml we are using.
https://github.com/pyvista/pyvista/blob/d3a51becf51cc7348e3c4c11ec6db170c2427f74/.github/workflows/label.yml
@mheap  I would appreciate your opinion about this.

**Comment by mheap** [comment]
If you're adding a label in the same workflow, you'll need to provide a `GITHUB_TOKEN` to check labels with the API

See https://github.com/mheap/github-action-required-labels#complete-example

```yaml
- uses: mheap/github-action-required-labels@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    mode: exactly
    count: 1
    labels: "semver:patch, semver:minor, semver:major"
```
