### ISSUE TITLE
Upgrade to v3 : `Resource not accessible by integration`

### ISSUE THREAD

**Issue by RobinMaronier** [mheap/github-action-required-labels#49]
Hi @mheap,

When i'm upgrading action to v3 from v2, I have the error `Resource not accessible by integration`. Everything works fine with v1 & v2.
Did I miss something ?

Thanks !!

**Comment by QcFe** [comment]
Same issue here...

**Comment by mheap** [comment]
Could you both please link to the workflow that you're using?

**Comment by QcFe** [comment]
Mine is currently on a private repository (that will be made public in a while but I cannot open it right now). Here's the workflow:
```yaml
name: Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  label: 
    name: Ensure PR not in hold
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "pr-hold"
```
I attach the output from the action:
![image](https://user-images.githubusercontent.com/10742159/228474341-2cdba55e-b397-49cb-a406-32b80b5345d5.png)

**Comment by RobinMaronier** [comment]
Hi !
Private repo as well 😕 

```
name: Mandatory labels

on:
  pull_request:
    types: [ labeled, unlabeled, opened, edited, synchronize ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "xx"
```

**Comment by QcFe** [comment]
Then I guess it could happen in case of private repos? I can't see any other difference at this point...

**Comment by mheap** [comment]
Found the issue. The `github.token` used to have implicit permissions and it no longer does.

Here's a workflow that worked for me with a private repo:

```yaml
name: Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  label: 
    name: Ensure PR not in hold
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - name: Check
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "pr-hold"
```

**Comment by ockham** [comment]
I was just facing a similar issue in our repo. FWIW, [the docs on GHA `permissions`](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) state:

>  `issues`: Work with issues. For example, `issues: write` permits an action to add a comment to an issue.
> `pull-requests`: Work with pull requests. For example, `pull-requests: write` permits an action to add a label to a pull request.

This means that the [suggested workaround](https://github.com/mheap/github-action-required-labels/issues/49#issuecomment-1492948272)

```yaml
    permissions:
      issues: read
      pull-requests: read
```

won't work with `add_comment` set to `true`, right? 

@mheap Would it make sense to document in the `README` that if people want the action to post comments to their PRs and issues, they'll need to provide a token that has `write` permissions for issues and PRs?
