### ISSUE TITLE
Action fails with "Not Found" when run in a merge queue

### ISSUE THREAD

**Issue by twyatt** [mheap/github-action-required-labels#66]
To reproduce, created a sample project repo at: https://github.com/JuulLabs/merge-queue-test

Without [merge queue] enabled, `github-action-required-labels` works (https://github.com/JuulLabs/merge-queue-test/pull/13) as expected:

<details>
<summary>GitHub Action run w/o merge queue</summary>

```
Run mheap/github-action-required-labels@v5
  with:
    mode: exactly
    count: 1
    labels: patch, minor, major, maintenance
    token: ***
    message: Label error. Requires {{errorString}} {{count}} of: {{ provided }}. Found: {{ applied }}
    add_comment: false
```

— https://github.com/JuulLabs/merge-queue-test/actions/runs/7154600875/job/19482310003
</details>

When [merge queue] is enabled, and `github-action-required-labels` runs from the queue, it fails (https://github.com/JuulLabs/merge-queue-test/pull/14) with:

```
Run mheap/github-action-required-labels@v5
  with:
    mode: exactly
    count: 1
    labels: patch, minor, major, maintenance
    token: ***
    message: Label error. Requires {{errorString}} {{count}} of: {{ provided }}. Found: {{ applied }}
    add_comment: false
Error: Not Found
```

— https://github.com/JuulLabs/merge-queue-test/actions/runs/7154628159/job/19482369364

[merge queue]: https://github.blog/2023-07-12-github-merge-queue-is-generally-available/
