### ISSUE TITLE
Prevent running the check after the PR has been closed?

### ISSUE THREAD

**Issue by aaronpk** [mheap/github-action-required-labels#7]
Is there a way to prevent the check from running after the PR has been closed? I couldn't find any filters on GitHub's docs to control that.

The issue is we're using this with a "Pending Merge" label, and we want to remove the label after the PR has been merged, but then the check runs and it sends an email about the failing check.

**Comment by mheap** [comment]
You can specify `types` under `pull_request` to choose which events. You probably want to set the following in your workflow:

```
on:
  pull_request:
    types: [opened, labeled, unlabeled]
```

**Comment by aaronpk** [comment]
Yeah, I have that set already. It's the "unlabeled" action that's triggering it. I do want the "unlabeled" action to run when the PR is open, but I don't want it to run after the PR is closed.

**Comment by mheap** [comment]
Ah sorry, missed that in the initial post.

You'll want an if statement similar to the following (I can't test right now):

```yaml
uses: mheap/github-action-required-labels@v1
if: github.event.pull_request.state == "open"
```

**Comment by aaronpk** [comment]
Wow thanks, I never would have figured that out on my own! It took digging through about 5 pages of GitHub docs to even be able to confirm the syntax for this, and in the end I had to guess and check the syntax. Here's what I'm using now:

```yaml
name: verify-pr-label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "Pending Merge, Editorial"
```

It skips the check earlier when the `if` is on the job instead of on the step. It also requires single quotes around the `open` value for some reason, double quotes threw a syntax error. Thanks!
