### ISSUE TITLE
Use label with regex

### ISSUE THREAD

**Issue by yaronkaikov** [mheap/github-action-required-labels#70]
I have multiple labels that can match, is there a way to use regex?

**Comment by mheap** [comment]
There is no regex support today. Can you share more information about your use case?

**Comment by yaronkaikov** [comment]
I am currently using this
```
name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "Backport not needed, Required Backport 5.4"
          add_comment: true
```

But I have multiple `Required Backport` labels for example with 5.4, 5.5, and act. Since this always changes, I don't want to maintain this, just use regex if available

**Comment by yaronkaikov** [comment]
Is there a plan to implement it? or some kind of a workaround ?

**Comment by mheap** [comment]
I've just released `v5.3.0` with regex support

Try this:

```yaml
name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "Backport not needed\n Required Backport \d\.\d"
          use_regex: true
          add_comment: true
```

Note that regex labels must be newline delimited, not comma separated

**Comment by yaronkaikov** [comment]
Thanks @mheap , it doesn't seem to work yet, I have this configuration
```
name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "backport/none\n backport \\d.\\d"
          use_regex: true
          add_comment: true
```

When i set the label to be `backport/none` it's working as expected 
![image](https://github.com/mheap/github-action-required-labels/assets/9914527/31fbc865-3f7a-43a2-aafa-5fb95e9218e1)


But when i set it to `backport 5.2` it's not 
```
![image](https://github.com/mheap/github-action-required-labels/assets/9914527/1d0aeb4a-c1b8-4ab1-bcbf-761446c811d6)
