### ISSUE TITLE
mode: n-of

### ISSUE THREAD

**Issue by katexochen** [mheap/github-action-required-labels#89]
Add a mode where exactly `count` labels of the listed must be applied.

The most common use case would be to set `count: 1`, so this is a one-of, where exactly one of the listed labels must be applied, and the action will fail if there are two applied. Setting other, unlisted labels should still be allowed.

Use case:
I want to choose a changelog category via label. Each PR needs exactly one of the changelog categories as label, but might have other labels (indicating size, backporting etc.)

**Comment by mheap** [comment]
It's been a little while, but isn't this what `exactly` provides?

```yaml
- uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            semver:patch
            semver:minor
            semver:major
```

The PR must have exactly one of these labels, and it will ignore any other labels
